package com.gama;

import java.util.List;

import org.hsqldb.util.DatabaseManagerSwing;

import com.gama.model.Contato;
import com.gama.repository.ContatoJdbcRepository;
import com.gama.repository.ContatoJpaRepository;

public class ContatoApp {
	public static void main(String[] args) {
		verBanco();
		//jdbc();
	}
	public static void verBanco() {
		//create table tab_contato (id integer generated by default as identity (start with 1), nome varchar(255), telefone varchar(255), primary key (id))
		final String[] dbms = { "--user", "SA", "--url", "jdbc:hsqldb:file:/temp/db/sampledb" };
		DatabaseManagerSwing.main(dbms);
		
	}
	public static void jdbc() {
		
		ContatoJdbcRepository repository = new ContatoJdbcRepository();
		
		Contato contato = new Contato();
		contato.setNome("GLEYSON");
		contato.setTelefone("11 8798798798");
		
		repository.incluir(contato);
		
		contato = new Contato();
		contato.setNome("JEFERSON");
		contato.setTelefone("11 9879879878");
		
		repository.incluir(contato);
		
		repository.fechar();
		
	}
	
	public static void jpa() {
		
		ContatoJpaRepository repository = new ContatoJpaRepository();
		
		Contato contato = new Contato();
		contato.setNome("GLEYSON");
		contato.setTelefone("11 8798798798");
		
		repository.incluir(contato);
		
		contato = new Contato();
		contato.setNome("JEFERSON");
		contato.setTelefone("11 9879879878");
		
		repository.incluir(contato);
		
		List<Contato> contatos = repository.listar();
		
		
		for(Contato c: contatos) {
			System.out.println(c.getId() + " -- " + c.getNome());
		}
	}
	
}
